### PR TITLE
Sync latest stweaks changes

### PR DESCRIPTION
**Pull request by gsstudios**
- Updated descriptions - Fixes to spelling errors, reorganization of settings
- Update profiles - Fix stability of performance profiles, improved battery life and performance
- Force zzmoove to use selected hotplug method

### CODE REVIEW

**Comment by dragonGR** [comment]
Thanks.

**Comment by dragonGR** [comment]
You included hotplugs. Hotplugs needs any commits in kernel?

**Comment by gsstudios** [comment]
No commits required. The changes uses the same tunables.

**Comment by dragonGR** [comment]
Alright, you planning to PR more stuff or is time to release v8.60? :P

**Comment by gsstudios** [comment]
It should be fine to release 8.60. Was going to fix up selinux, but there's too many changes I will have to worry about (and also fragmentation of code between JB and MM) :)

**Comment by dragonGR** [comment]
What do you mean fragmentation? Also, Selinux have no power on JB.

**Comment by gsstudios** [comment]
It seems that JB is missing a few commits from KK and MM kernels. This is stopping me from cleanly applying the patches, hence it will require a bit of work to fix up. Not important to re-enable selinux but it was a shot anyway.

**Comment by dragonGR** [comment]
May can i help?

**Comment by gsstudios** [comment]
Sure, right now compiling with selinux flags will cause a build error because of unmerged changes. Compiler errors were fixed with this: https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/commit/5b9e25e24b8ae42457149c9a8cd5960906c30ae7

There were some other commits after that should be merged with the fixes as well.

**Comment by dragonGR** [comment]
selinux is useless unless we're working on KK. Plus, SELinux have no power on JB.

**Comment by gsstudios** [comment]
^^^ Pretty much this

**Comment by dragonGR** [comment]
Oh i also forgot, When i try to increase Headphone sound via STweaks(Sound tab), it does nothing, it increase a biit(just a bit), this never happened on KK,LP,MM. 
I suspect is the drivers.

**Comment by gsstudios** [comment]
I will be making one pull request soon for one minor change I made today

**Comment by dragonGR** [comment]
The HZ thing on wifi driver i guess, merged.

Is necessary to update wifi/audio driver on JB  or the current ones is fine?

**Comment by gsstudios** [comment]
Wifi driver doesn't really need updating. I could update it but I can't help test it out. 

The audio driver should be fine.

**Comment by dragonGR** [comment]
So the sound thing on stweaks remains unsolved mystery, :P

**Comment by gsstudios** [comment]
For now. I'll have a look later

**Comment by dragonGR** [comment]
Ok. Compiling now...

**Pull request merged**
